direction: down

classes: {
  label_bg: {
    shape: text
    style: {
      stroke-width: 015
      font-color: "#003311"
      font-size: 18
    }
  }
}
src_components_editor_menus_dropdownmenu_jsx -> label_0 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_0 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_menus_editmenu_jsx -> label_1 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_1 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_menus_editmenu_jsx -> label_2 { style: { stroke: "#808080" } }
label_2 -> src_components_editor_menus_dropdownmenu_jsx   { style: { stroke: "#808080" } }
src_components_editor_menus_filemenu_jsx -> label_4 { style: { stroke: "#808080" } }
label_4 -> src_components_editor_menus_dropdownmenu_jsx   { style: { stroke: "#808080" } }
src_components_editor_menus_filemenu_jsx -> label_3 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_3 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_editor_jsx -> label_6 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_6 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_editor_jsx -> label_7 { style: { stroke: "#808080" } }
label_7 -> monaco-editor_react   { style: { stroke: "#808080" } }
src_components_codeviewer_jsx -> label_28 { style: { stroke: "#808080" } }
label_28 -> monaco-editor_react   { style: { stroke: "#808080" } }
src_components_codeviewer_jsx -> label_27 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_27 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_editorheader_jsx -> label_16 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_16 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_editor_jsx -> label_8 { style: { stroke: "#808080" } }
label_8 -> src_components_editor_editorheader_jsx   { style: { stroke: "#808080" } }
src_components_editor_editor_jsx -> label_9 { style: { stroke: "#808080" } }
label_9 -> src_components_editor_errorlistportal_jsx   { style: { stroke: "#808080" } }
src_components_editor_errorlistportal_jsx -> label_24 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_24 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_erroritem_jsx -> label_19 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_19 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_erroritem_jsx -> label_20 { style: { stroke: "#808080" } }
label_20 -> src_app_css   { style: { stroke: "#808080" } }
src_components_editor_editor_jsx -> label_13 { style: { stroke: "#808080" } }
label_13 -> src_app_css   { style: { stroke: "#808080" } }
src_components_editor_editor_jsx -> label_10 { style: { stroke: "#808080" } }
label_10 -> src_components_editor_utils_formatcode_js   { style: { stroke: "#808080" } }
src_components_editor_editor_jsx -> label_11 { style: { stroke: "#808080" } }
label_11 -> src_components_editor_utils_seterrors_js   { style: { stroke: "#808080" } }
src_components_editor_editor_jsx -> label_12 { style: { stroke: "#808080" } }
label_12 -> src_components_editor_utils_monacosetup_js   { style: { stroke: "#808080" } }
src_components_editor_utils_monacosetup_js -> label_5 { style: { stroke: "#808080" } }
label_5 -> src_utils_tokenparser_js   { style: { stroke: "#808080" } }
src_utils_tokenparser_js -> label_38 { style: { stroke: "#808080" } }
label_38 -> src_utils_lexer_js   { style: { stroke: "#808080" } }
src_utils_lexer_js -> label_37 { style: { stroke: "#808080" } }
label_37 -> src_utils_tokens_js   { style: { stroke: "#808080" } }
src_utils_tokenparser_js -> label_39 { style: { stroke: "#808080" } }
label_39 -> src_utils_tokens_js   { style: { stroke: "#808080" } }
src_utils_tokenparser_js -> label_40 { style: { stroke: "#808080" } }
label_40 -> src_utils_utils_js   { style: { stroke: "#808080" } }
src_utils_validation_js -> label_42 { style: { stroke: "#808080" } }
label_42 -> src_utils_utils_js   { style: { stroke: "#808080" } }
src_utils_tokenparser_js -> label_41 { style: { stroke: "#808080" } }
label_41 -> src_utils_validation_js   { style: { stroke: "#808080" } }
src_app_jsx -> label_47 { style: { stroke: "#808080" } }
label_47 -> src_utils_tokenparser_js   { style: { stroke: "#808080" } }
src_app_jsx -> label_43 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_43 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_errorlist_jsx -> label_21 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_21 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_errorlist_jsx -> label_22 { style: { stroke: "#808080" } }
label_22 -> src_app_css   { style: { stroke: "#808080" } }
src_components_rendererd2_jsx -> label_32 { style: { stroke: "#808080" } }
label_32 -> src_app_css   { style: { stroke: "#808080" } }
src_components_rendererd2_jsx -> label_30 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_30 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_rendermodal_jsx -> label_34 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_34 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_rendererd2_jsx -> label_33 { style: { stroke: "#808080" } }
label_33 -> src_components_rendermodal_jsx   { style: { stroke: "#808080" } }
src_components_rendererd2_jsx -> label_31 { style: { stroke: "#808080" } }
label_31 -> src_components_codeviewer_jsx   { style: { stroke: "#808080" } }
src_components_codeviewer_jsx -> label_29 { style: { stroke: "#808080" } }
label_29 -> src_components_editor_utils_monacosetup_js   { style: { stroke: "#808080" } }
src_app_jsx -> label_46 { style: { stroke: "#808080" } }
label_46 -> src_components_rendererd2_jsx   { style: { stroke: "#808080" } }
src_app_jsx -> label_44 { style: { stroke: "#4F8A10"
    stroke-dash: 5 } }
label_44 -> lodash   { style: { stroke: "#4F8A10"
    stroke-dash: 5 } }
src_components_editor_editor_jsx -> label_14 { style: { stroke: "#4F8A10"
    stroke-dash: 5 } }
label_14 -> lodash   { style: { stroke: "#4F8A10"
    stroke-dash: 5 } }
src_components_editor_editor_jsx -> label_15 { style: { stroke: "lightgreen"
    stroke-dash: 5 } }
label_15 -> file-saver   { style: { stroke: "lightgreen"
    stroke-dash: 5 } }
src_app_jsx -> label_45 { style: { stroke: "#808080" } }
label_45 -> src_components_editor_editor_jsx   { style: { stroke: "#808080" } }
src_app_jsx -> label_48 { style: { stroke: "#808080" } }
label_48 -> src_app_css   { style: { stroke: "#808080" } }
src_main_jsx -> label_51 { style: { stroke: "#808080" } }
label_51 -> src_app_jsx   { style: { stroke: "#808080" } }
src_main_jsx -> label_49 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_49 -> react   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_main_jsx -> label_50 { style: { stroke: "#808080" } }
label_50 -> react-dom_client   { style: { stroke: "#808080" } }
src_main_jsx -> label_52 { style: { stroke: "#808080" } }
label_52 -> src_index_css   { style: { stroke: "#808080" } }
index_html -> label_53 { style: { stroke: "#808080" } }
label_53 -> src_main_jsx   { style: { stroke: "#808080" } }
src_components_rendermodal_jsx -> label_35 { style: { stroke: "#808080" } }
label_35 -> terrastruct_d2   { style: { stroke: "#808080" } }
src_components_rendermodal_jsx -> label_36 { style: { stroke: "#808080" } }
label_36 -> svg-pan-zoom   { style: { stroke: "#808080" } }
src_components_editor_errorlist_jsx -> label_23 { style: { stroke: "#808080" } }
label_23 -> src_components_editor_erroritem_jsx   { style: { stroke: "#808080" } }
src_components_editor_errorlistportal_jsx -> label_26 { style: { stroke: "#808080" } }
label_26 -> src_components_editor_errorlist_jsx   { style: { stroke: "#808080" } }
src_components_editor_errorlistportal_jsx -> label_25 { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
label_25 -> react-dom   { style: { stroke: "#61DAFB"
    stroke-dash: 5 } }
src_components_editor_editorheader_jsx -> label_17 { style: { stroke: "#808080" } }
label_17 -> src_components_editor_menus_filemenu_jsx   { style: { stroke: "#808080" } }
src_components_editor_editorheader_jsx -> label_18 { style: { stroke: "#808080" } }
label_18 -> src_components_editor_menus_editmenu_jsx   { style: { stroke: "#808080" } }
vite_config_js -> label_54 { style: { stroke: "#808080" } }
label_54 -> vite   { style: { stroke: "#808080" } }
vite_config_js -> label_55 { style: { stroke: "#808080" } }
label_55 -> vitejs_plugin-react-refresh   { style: { stroke: "#808080" } }
src_components_editor_menus_dropdownmenu_jsx: "src_components_editor_menus_dropdownmenu_jsx\n(46 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_components_editor_menus_editmenu_jsx: "src_components_editor_menus_editmenu_jsx\n(15 lines)" { style: { stroke-width: 1 }
 shape: "rectangle" }
src_components_editor_menus_filemenu_jsx: "src_components_editor_menus_filemenu_jsx\n(15 lines)" { style: { stroke-width: 1 }
 shape: "rectangle" }
src_components_editor_utils_exampleuitd_js: "src_components_editor_utils_exampleuitd_js\n(46 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_components_editor_utils_formatcode_js: "src_components_editor_utils_formatcode_js\n(71 lines)" { style: { stroke-width: 3 }
 shape: "rectangle" }
src_components_editor_utils_monacosetup_js: "src_components_editor_utils_monacosetup_js\n(175 lines)" { style: { stroke-width: 7 }
 shape: "rectangle" }
src_components_editor_utils_seterrors_js: "src_components_editor_utils_seterrors_js\n(26 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_components_editor_editor_jsx: "src_components_editor_editor_jsx\n(352 lines)" { style: { stroke-width: 13 }
 shape: "rectangle" }
src_components_editor_editorheader_jsx: "src_components_editor_editorheader_jsx\n(106 lines)" { style: { stroke-width: 4 }
 shape: "rectangle" }
src_components_editor_erroritem_jsx: "src_components_editor_erroritem_jsx\n(45 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_components_editor_errorlist_jsx: "src_components_editor_errorlist_jsx\n(32 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_components_editor_errorlistportal_jsx: "src_components_editor_errorlistportal_jsx\n(14 lines)" { style: { stroke-width: 1 }
 shape: "rectangle" }
src_components_codeviewer_jsx: "src_components_codeviewer_jsx\n(36 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_components_rendererd2_jsx: "src_components_rendererd2_jsx\n(315 lines)" { style: { stroke-width: 12 }
 shape: "rectangle" }
src_components_rendermodal_jsx: "src_components_rendermodal_jsx\n(224 lines)" { style: { stroke-width: 9 }
 shape: "rectangle" }
src_utils_lexer_js: "src_utils_lexer_js\n(100 lines)" { style: { stroke-width: 4 }
 shape: "rectangle" }
src_utils_tokenparser_js: "src_utils_tokenparser_js\n(404 lines)" { style: { stroke-width: 15 }
 shape: "rectangle" }
src_utils_tokens_js: "src_utils_tokens_js\n(48 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_utils_utils_js: "src_utils_utils_js\n(34 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_utils_validation_js: "src_utils_validation_js\n(268 lines)" { style: { stroke-width: 10 }
 shape: "rectangle" }
src_app_css: "src_app_css\n(304 lines)" { style: { stroke-width: 11 }
 shape: "rectangle" }
src_app_jsx: "src_app_jsx\n(46 lines)" { style: { stroke-width: 2 }
 shape: "rectangle" }
src_index_css: "src_index_css\n(75 lines)" { style: { stroke-width: 3 }
 shape: "rectangle" }
src_main_jsx: "src_main_jsx\n(11 lines)" { style: { stroke-width: 1 }
 shape: "rectangle" }
index_html: "index_html\n(20 lines)" { style: { stroke-width: 1 }
 shape: "rectangle" }
vite_config_js: "vite_config_js\n(15 lines)" { style: { stroke-width: 1 }
 shape: "rectangle" }
react: "react" { style: { stroke-width: 1 }
 shape: "hexagon" }
monaco-editor_react: "@monaco-editor_react" { style: { stroke-width: 1 }
 shape: "oval" }
lodash: "lodash" { style: { stroke-width: 1 }
 shape: "oval" }
file-saver: "file-saver" { style: { stroke-width: 1 }
 shape: "oval" }
react-dom: "react-dom" { style: { stroke-width: 1 }
 shape: "hexagon" }
terrastruct_d2: "@terrastruct_d2" { style: { stroke-width: 1 }
 shape: "oval" }
svg-pan-zoom: "svg-pan-zoom" { style: { stroke-width: 1 }
 shape: "oval" }
react-dom_client: "react-dom_client" { style: { stroke-width: 1 }
 shape: "oval" }
vite: "vite" { style: { stroke-width: 1 }
 shape: "oval" }
vitejs_plugin-react-refresh: "@vitejs_plugin-react-refresh" { style: { stroke-width: 1 }
 shape: "oval" }
label_0: "React,\nuseState,\nuseRef,\nuseEffect" 
label_0.class: label_bg
label_1: "React" 
label_1.class: label_bg
label_2: "DropdownMenu" 
label_2.class: label_bg
label_3: "React" 
label_3.class: label_bg
label_4: "DropdownMenu" 
label_4.class: label_bg
label_5: "validVerbs" 
label_5.class: label_bg
label_6: "React,\nuseRef,\nuseState,\nuseEffect,\nuseCallback" 
label_6.class: label_bg
label_7: "MonacoEditor" 
label_7.class: label_bg
label_8: "EditorHeader" 
label_8.class: label_bg
label_9: "ErrorListPortal" 
label_9.class: label_bg
label_10: "handleFormatCode" 
label_10.class: label_bg
label_11: "setErrors" 
label_11.class: label_bg
label_12: "setupMonaco" 
label_12.class: label_bg
label_13: "_" 
label_13.class: label_bg
label_14: "debounce" 
label_14.class: label_bg
label_15: "saveAs" 
label_15.class: label_bg
label_16: "React,\nuseState,\nuseEffect,\nuseCallback" 
label_16.class: label_bg
label_17: "FileMenu" 
label_17.class: label_bg
label_18: "EditMenu" 
label_18.class: label_bg
label_19: "React" 
label_19.class: label_bg
label_20: "_" 
label_20.class: label_bg
label_21: "React" 
label_21.class: label_bg
label_22: "_" 
label_22.class: label_bg
label_23: "ErrorItem" 
label_23.class: label_bg
label_24: "React" 
label_24.class: label_bg
label_25: "createPortal" 
label_25.class: label_bg
label_26: "ErrorList" 
label_26.class: label_bg
label_27: "React,\nuseCallback,\nuseRef" 
label_27.class: label_bg
label_28: "MonacoEditor" 
label_28.class: label_bg
label_29: "setupD2" 
label_29.class: label_bg
label_30: "React,\nuseState,\nuseRef,\nuseEffect,\nuseCallback" 
label_30.class: label_bg
label_31: "CodeViewer" 
label_31.class: label_bg
label_32: "_" 
label_32.class: label_bg
label_33: "RenderModal" 
label_33.class: label_bg
label_34: "React,\nuseState,\nuseRef,\nuseEffect,\nuseLayoutEffect" 
label_34.class: label_bg
label_35: "D2" 
label_35.class: label_bg
label_36: "svgPanZoom" 
label_36.class: label_bg
label_37: "Token,\nTokenType,\nTokens" 
label_37.class: label_bg
label_38: "tokenize" 
label_38.class: label_bg
label_39: "TokenType" 
label_39.class: label_bg
label_40: "getInnermostUIStr,\ngetInnermostUIRef,\nformatUIRef" 
label_40.class: label_bg
label_41: "validateData" 
label_41.class: label_bg
label_42: "getInnermostUIRef,\nformatUIRef" 
label_42.class: label_bg
label_43: "React,\nuseState,\nuseEffect,\nuseMemo" 
label_43.class: label_bg
label_44: "debounce" 
label_44.class: label_bg
label_45: "Editor" 
label_45.class: label_bg
label_46: "RendererD2" 
label_46.class: label_bg
label_47: "parseUITDL" 
label_47.class: label_bg
label_48: "_" 
label_48.class: label_bg
label_49: "React" 
label_49.class: label_bg
label_50: "ReactDOM" 
label_50.class: label_bg
label_51: "App" 
label_51.class: label_bg
label_52: "_" 
label_52.class: label_bg
label_53: "_" 
label_53.class: label_bg
label_54: "defineConfig" 
label_54.class: label_bg
label_55: "reactRefresh" 
label_55.class: label_bg