direction: down
app_css: "../\nApp.css\n(226 lines)" { style: { stroke-width: 9 } }
app_jsx: "../\nApp.jsx\n(40 lines)" { style: { stroke-width: 2 } }
components_codeviewer_jsx: "../\ncomponents/\nCodeViewer.jsx\n(24 lines)" { style: { stroke-width: 1 } }
components_editor_editor_jsx: "../\ncomponents/\nEditor/\nEditor.jsx\n(115 lines)" { style: { stroke-width: 5 } }
components_editor_editorheader_jsx: "../\ncomponents/\nEditor/\nEditorHeader.jsx\n(44 lines)" { style: { stroke-width: 2 } }
components_editor_errorlist_jsx: "../\ncomponents/\nEditor/\nErrorList.jsx\n(35 lines)" { style: { stroke-width: 2 } }
components_editor_menus_dropdownmenu_jsx: "../\ncomponents/\nEditor/\nmenus/\nDropdownMenu.jsx\n(40 lines)" { style: { stroke-width: 2 } }
components_editor_menus_editmenu_jsx: "../\ncomponents/\nEditor/\nmenus/\nEditMenu.jsx\n(47 lines)" { style: { stroke-width: 2 } }
components_editor_menus_filemenu_jsx: "../\ncomponents/\nEditor/\nmenus/\nFileMenu.jsx\n(58 lines)" { style: { stroke-width: 3 } }
components_editor_utils_exampleuitd_js: "../\ncomponents/\nEditor/\nutils/\nExampleUITD.js\n(45 lines)" { style: { stroke-width: 2 } }
components_editor_utils_formatcode_js: "../\ncomponents/\nEditor/\nutils/\nformatCode.js\n(68 lines)" { style: { stroke-width: 3 } }
components_editor_utils_monacosetup_js: "../\ncomponents/\nEditor/\nutils/\nmonacoSetup.js\n(91 lines)" { style: { stroke-width: 4 } }
components_editor_utils_seterrors_js: "../\ncomponents/\nEditor/\nutils/\nsetErrors.js\n(24 lines)" { style: { stroke-width: 1 } }
components_rendererd2_jsx: "../\ncomponents/\nRendererD2.jsx\n(184 lines)" { style: { stroke-width: 7 } }
index_css: "../\nindex.css\n(75 lines)" { style: { stroke-width: 3 } }
main_jsx: "../\nmain.jsx\n(11 lines)" { style: { stroke-width: 1 } }
utils_lexer_js: "../\nutils/\nlexer.js\n(100 lines)" { style: { stroke-width: 4 } }
utils_tokenparser_js: "../\nutils/\nTokenParser.js\n(392 lines)" { style: { stroke-width: 15 } }
utils_tokens_js: "../\nutils/\ntokens.js\n(48 lines)" { style: { stroke-width: 2 } }
utils_utils_js: "../\nutils/\nutils.js\n(34 lines)" { style: { stroke-width: 2 } }
utils_validation_js: "../\nutils/\nvalidation.js\n(268 lines)" { style: { stroke-width: 10 } }
react: "react" { style: { stroke-width: 1 } }
_monaco_editor_react: "@monaco-editor/react" { style: { stroke-width: 1 } }
file_saver: "file-saver" { style: { stroke-width: 1 } }
react_dom_client: "react-dom/client" { style: { stroke-width: 1 } }
app_jsx -> react: "React,\nuseState,\nuseEffect"
app_jsx -> components_editor_editor_jsx: "Editor"
app_jsx -> components_rendererd2_jsx: "RendererD2"
app_jsx -> components_editor_utils_exampleuitd_js: "ExampleUITD"
app_jsx -> utils_tokenparser_js: "parseUITDL"
app_jsx -> app_css
components_codeviewer_jsx -> react: "React"
components_codeviewer_jsx -> _monaco_editor_react: "MonacoEditor"
components_editor_editor_jsx -> react: "React,\nuseRef,\nuseState,\nuseEffect"
components_editor_editor_jsx -> _monaco_editor_react: "MonacoEditor"
components_editor_editor_jsx -> components_editor_errorlist_jsx: "ErrorList"
components_editor_editor_jsx -> components_editor_editorheader_jsx: "EditorHeader"
components_editor_editor_jsx -> components_editor_utils_formatcode_js: "handleFormatCode"
components_editor_editor_jsx -> components_editor_utils_seterrors_js: "setErrors"
components_editor_editor_jsx -> components_editor_utils_monacosetup_js: "setupMonaco"
components_editor_editor_jsx -> app_css
components_editor_editorheader_jsx -> react: "React"
components_editor_editorheader_jsx -> components_editor_menus_filemenu_jsx: "FileMenu"
components_editor_editorheader_jsx -> components_editor_menus_editmenu_jsx: "EditMenu"
components_editor_errorlist_jsx -> react: "React"
components_editor_errorlist_jsx -> app_css
components_editor_menus_dropdownmenu_jsx -> react: "React,\nuseState"
components_editor_menus_editmenu_jsx -> react: "React"
components_editor_menus_editmenu_jsx -> components_editor_menus_dropdownmenu_jsx: "DropdownMenu"
components_editor_menus_editmenu_jsx -> components_editor_utils_exampleuitd_js: "ExampleUITD"
components_editor_menus_filemenu_jsx -> react: "React,\nuseRef"
components_editor_menus_filemenu_jsx -> file_saver: "saveAs"
components_editor_menus_filemenu_jsx -> components_editor_menus_dropdownmenu_jsx: "DropdownMenu"
components_editor_utils_monacosetup_js -> utils_tokenparser_js: "validVerbs"
components_rendererd2_jsx -> react: "React,\nuseEffect,\nuseState"
components_rendererd2_jsx -> components_codeviewer_jsx: "CodeViewer"
components_rendererd2_jsx -> app_css
main_jsx -> react: "React"
main_jsx -> react_dom_client: "ReactDOM"
main_jsx -> app_jsx: "App"
main_jsx -> index_css
utils_lexer_js -> utils_tokens_js: "Token,\nTokenType,\nTokens"
utils_tokenparser_js -> utils_lexer_js: "tokenize"
utils_tokenparser_js -> utils_tokens_js: "TokenType"
utils_tokenparser_js -> utils_utils_js: "getInnermostUIStr,\ngetInnermostUIRef,\nformatUIRef"
utils_tokenparser_js -> utils_validation_js: "validateData"
utils_validation_js -> utils_utils_js: "getInnermostUIRef,\nformatUIRef"