// React App Architecture
direction: down
app_css: "../\nApp.css\n(226 lines)"
app_jsx: "../\nApp.jsx\n(40 lines)"
components_codeviewer_jsx: "../\ncomponents/\nCodeViewer.jsx\n(24 lines)"
components_collapsible_jsx: "../\ncomponents/\nCollapsible.jsx\n(27 lines)"
components_d2language_js: "../\ncomponents/\nd2Language.js\n(96 lines)"
components_dropdownmenu_jsx: "../\ncomponents/\nDropdownMenu.jsx\n(24 lines)"
components_editor_editor_jsx: "../\ncomponents/\nEditor/\nEditor.jsx\n(115 lines)"
components_editor_editorheader_jsx: "../\ncomponents/\nEditor/\nEditorHeader.jsx\n(44 lines)"
components_editor_errorlist_jsx: "../\ncomponents/\nEditor/\nErrorList.jsx\n(35 lines)"
components_editor_errorpopup_jsx: "../\ncomponents/\nEditor/\nErrorPopup.jsx\n(28 lines)"
components_editor_menus_dropdownmenu_jsx: "../\ncomponents/\nEditor/\nmenus/\nDropdownMenu.jsx\n(40 lines)"
components_editor_menus_editmenu_jsx: "../\ncomponents/\nEditor/\nmenus/\nEditMenu.jsx\n(47 lines)"
components_editor_menus_filemenu_jsx: "../\ncomponents/\nEditor/\nmenus/\nFileMenu.jsx\n(58 lines)"
components_editor_utils_exampleuitd_js: "../\ncomponents/\nEditor/\nutils/\nExampleUITD.js\n(45 lines)"
components_editor_utils_formatcode_js: "../\ncomponents/\nEditor/\nutils/\nformatCode.js\n(68 lines)"
components_editor_utils_monacosetup_js: "../\ncomponents/\nEditor/\nutils/\nmonacoSetup.js\n(91 lines)"
components_editor_utils_seterrors_js: "../\ncomponents/\nEditor/\nutils/\nsetErrors.js\n(24 lines)"
components_editor_jsx: "../\ncomponents/\nEditor.jsx\n(372 lines)"
components_renderer_jsx: "../\ncomponents/\nRenderer.jsx\n(156 lines)"
components_rendererd2_jsx: "../\ncomponents/\nRendererD2.jsx\n(184 lines)"
components_rendererparsed_jsx: "../\ncomponents/\nRendererParsed.jsx\n(18 lines)"
components_transition_jsx: "../\ncomponents/\nTransition.jsx\n(91 lines)"
components_ui_jsx: "../\ncomponents/\nUI.jsx\n(36 lines)"
index_css: "../\nindex.css\n(75 lines)"
main_jsx: "../\nmain.jsx\n(11 lines)"
utils_lexer_js: "../\nutils/\nlexer.js\n(100 lines)"
utils_parser_jsx: "../\nutils/\nParser.jsx\n(406 lines)"
utils_tokenparser_js: "../\nutils/\nTokenParser.js\n(392 lines)"
utils_tokens_js: "../\nutils/\ntokens.js\n(48 lines)"
utils_utils_js: "../\nutils/\nutils.js\n(34 lines)"
utils_validation_js: "../\nutils/\nvalidation.js\n(268 lines)"
utils_webappgenerator_jsx: "../\nutils/\nwebAppGenerator.jsx\n(202 lines)"
react: "react"
_monaco_editor_react: "@monaco-editor/react"
react_collapse: "react-collapse"
file_saver: "file-saver"
react_resizable_css_styles_css: "react-resizable/css/styles.css"
react_konva: "react-konva"
react_dom_client: "react-dom/client"
app_jsx -> react: "React,\nuseState,\nuseEffect"
app_jsx -> components_editor_editor_jsx: "Editor"
app_jsx -> components_rendererd2_jsx: "RendererD2"
app_jsx -> components_editor_utils_exampleuitd_js: "ExampleUITD"
app_jsx -> utils_tokenparser_js: "parseUITDL"
app_jsx -> app_css
components_codeviewer_jsx -> react: "React"
components_codeviewer_jsx -> _monaco_editor_react: "MonacoEditor"
components_collapsible_jsx -> react: "React,\nuseState"
components_collapsible_jsx -> react_collapse: "Collapse"
components_dropdownmenu_jsx -> react: "React"
components_editor_editor_jsx -> react: "React,\nuseRef,\nuseState,\nuseEffect"
components_editor_editor_jsx -> _monaco_editor_react: "MonacoEditor"
components_editor_editor_jsx -> components_editor_errorlist_jsx: "ErrorList"
components_editor_editor_jsx -> components_editor_editorheader_jsx: "EditorHeader"
components_editor_editor_jsx -> components_editor_utils_formatcode_js: "handleFormatCode"
components_editor_editor_jsx -> components_editor_utils_seterrors_js: "setErrors"
components_editor_editor_jsx -> components_editor_utils_monacosetup_js: "setupMonaco"
components_editor_editor_jsx -> app_css
components_editor_editorheader_jsx -> react: "React"
components_editor_editorheader_jsx -> components_editor_menus_filemenu_jsx: "FileMenu"
components_editor_editorheader_jsx -> components_editor_menus_editmenu_jsx: "EditMenu"
components_editor_errorlist_jsx -> react: "React"
components_editor_errorlist_jsx -> app_css
components_editor_errorpopup_jsx -> react: "React"
components_editor_errorpopup_jsx -> app_css
components_editor_menus_dropdownmenu_jsx -> react: "React,\nuseState"
components_editor_menus_editmenu_jsx -> react: "React"
components_editor_menus_editmenu_jsx -> components_editor_menus_dropdownmenu_jsx: "DropdownMenu"
components_editor_menus_editmenu_jsx -> components_editor_utils_exampleuitd_js: "ExampleUITD"
components_editor_menus_filemenu_jsx -> react: "React,\nuseRef"
components_editor_menus_filemenu_jsx -> file_saver: "saveAs"
components_editor_menus_filemenu_jsx -> components_editor_menus_dropdownmenu_jsx: "DropdownMenu"
components_editor_utils_monacosetup_js -> utils_tokenparser_js: "validVerbs"
components_editor_jsx -> react: "React,\nuseRef,\nuseState,\nuseEffect"
components_editor_jsx -> _monaco_editor_react: "MonacoEditor"
components_editor_jsx -> react_resizable_css_styles_css
components_editor_jsx -> utils_tokenparser_js: "validVerbs"
components_editor_jsx -> file_saver: "saveAs"
components_editor_jsx -> components_editor_utils_exampleuitd_js: "ExampleUITD"
components_editor_jsx -> app_css
components_editor_jsx -> components_dropdownmenu_jsx: "DropdownMenu"
components_renderer_jsx -> react: "React,\nuseRef,\nuseEffect"
components_rendererd2_jsx -> react: "React,\nuseEffect,\nuseState"
components_rendererd2_jsx -> components_codeviewer_jsx: "CodeViewer"
components_rendererd2_jsx -> app_css
components_rendererparsed_jsx -> react: "React"
components_transition_jsx -> react: "React"
components_transition_jsx -> react_konva: "Group,\nLine,\nArrow,\nText"
components_transition_jsx -> utils_utils_js: "resolveNestedPosition"
components_ui_jsx -> react: "React"
components_ui_jsx -> react_konva: "Group,\nRect,\nText"
components_ui_jsx -> utils_utils_js: "calculateUIHeight,\ncalculateUIWidth"
main_jsx -> react: "React"
main_jsx -> react_dom_client: "ReactDOM"
main_jsx -> app_jsx: "App"
main_jsx -> index_css
utils_lexer_js -> utils_tokens_js: "Token,\nTokenType,\nTokens"
utils_parser_jsx -> utils_utils_js: "getInnermostUI"
utils_tokenparser_js -> utils_lexer_js: "tokenize"
utils_tokenparser_js -> utils_tokens_js: "TokenType"
utils_tokenparser_js -> utils_utils_js: "getInnermostUIStr,\ngetInnermostUIRef,\nformatUIRef"
utils_tokenparser_js -> utils_validation_js: "validateData"
utils_validation_js -> utils_utils_js: "getInnermostUIRef,\nformatUIRef"