direction: right

vars: {
  ui0: {
    fill: "#ffd6e6"
    stroke: "#4b2e83"
  }
  ui1: {
    fill: "#e6ccb3"
    stroke: "#911eb4"
  }
  ui2: {
    fill: "#b3fff9"
    stroke: "#b3b300"
  }
  ui3: {
    fill: "#ffd9b3"
    stroke: "#cc7a00"
  }
  ui4: {
    fill: "#ffe6cc"
    stroke: "#666666"
  }
  ui5: {
    fill: "#ffe6f3"
    stroke: "#008000"
  }
  ui6: {
    fill: "#ffd9b3"
    stroke: "#c71585"
  }
  ui7: {
    fill: "#b3c6ff"
    stroke: "#3cb44b"
  }
  ui8: {
    fill: "#f3e6d7"
    stroke: "#5b3a29"
  }
  ui9: {
    fill: "#e6ccff"
    stroke: "#9a6324"
  }
  ui10: {
    fill: "#ffb3b3"
    stroke: "#a9a9a9"
  }
  ui11: {
    fill: "#cce0ff"
    stroke: "#f58231"
  }
  ui12: {
    fill: "#b3ffb3"
    stroke: "#e6e6e6"
  }
  ui13: {
    fill: "#ccfff9"
    stroke: "#ffd9b3"
  }
  ui14: {
    fill: "#ffe6cc"
    stroke: "#a83232"
  }
  ui15: {
    fill: "#ffffb3"
    stroke: "#e6ccff"
  }
  ui16: {
    fill: "#b3c6ff"
    stroke: "#174ea6"
  }
  ui17: {
    fill: "#f3e6ff"
    stroke: "#4363d8"
  }
  ui18: {
    fill: "#e6ccff"
    stroke: "#e6ccb3"
  }
  ui19: {
    fill: "#ccffcc"
    stroke: "#ffe6cc"
  }
  ui20: {
    fill: "#e6e6e6"
    stroke: "#b3c6ff"
  }
  ui21: {
    fill: "#cce0ff"
    stroke: "#ffe119"
  }
  ui22: {
    fill: "#ffffcc"
    stroke: "#e6194b"
  }
  ui23: {
    fill: "#ffcccc"
    stroke: "#ffffb3"
  }
  ui24: {
    fill: "#ffb3b3"
    stroke: "#f3e6ff"
  }
  ui25: {
    fill: "#ffffb3"
    stroke: "#fabebe"
  }
  ui26: {
    fill: "#ffd6e6"
    stroke: "#009999"
  }
  ui27: {
    fill: "#f3f3f3"
    stroke: "#ffd6e6"
  }
  ui28: {
    fill: "#ffcccc"
    stroke: "#b3ffb3"
  }
  ui29: {
    fill: "#ffffcc"
    stroke: "#42d4f4"
  }
  ui30: {
    fill: "#e6ccb3"
    stroke: "#b3fff9"
  }
  ui31: {
    fill: "#e6e6e6"
    stroke: "#ffb3b3"
  }
  ui32: {
    fill: "#f3e6ff"
    stroke: "#ffffcc"
  }
  ui33: {
    fill: "#b3ffb3"
    stroke: "#ffcccc"
  }
  ui34: {
    fill: "#b3fff9"
    stroke: "#cce0ff"
  }
}

# Classes generated for each UI
classes: {
  ui0: {
    shape: rectangle
    style: {
      fill: ${ui0.fill}
      stroke: ${ui0.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui1: {
    shape: rectangle
    style: {
      fill: ${ui1.fill}
      stroke: ${ui1.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui2: {
    shape: rectangle
    style: {
      fill: ${ui2.fill}
      stroke: ${ui2.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui3: {
    shape: rectangle
    style: {
      fill: ${ui3.fill}
      stroke: ${ui3.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui4: {
    shape: rectangle
    style: {
      fill: ${ui4.fill}
      stroke: ${ui4.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui5: {
    shape: rectangle
    style: {
      fill: ${ui5.fill}
      stroke: ${ui5.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui6: {
    shape: rectangle
    style: {
      fill: ${ui6.fill}
      stroke: ${ui6.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui7: {
    shape: rectangle
    style: {
      fill: ${ui7.fill}
      stroke: ${ui7.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui8: {
    shape: rectangle
    style: {
      fill: ${ui8.fill}
      stroke: ${ui8.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui9: {
    shape: rectangle
    style: {
      fill: ${ui9.fill}
      stroke: ${ui9.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui10: {
    shape: rectangle
    style: {
      fill: ${ui10.fill}
      stroke: ${ui10.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui11: {
    shape: rectangle
    style: {
      fill: ${ui11.fill}
      stroke: ${ui11.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui12: {
    shape: rectangle
    style: {
      fill: ${ui12.fill}
      stroke: ${ui12.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui13: {
    shape: rectangle
    style: {
      fill: ${ui13.fill}
      stroke: ${ui13.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui14: {
    shape: rectangle
    style: {
      fill: ${ui14.fill}
      stroke: ${ui14.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui15: {
    shape: rectangle
    style: {
      fill: ${ui15.fill}
      stroke: ${ui15.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui16: {
    shape: rectangle
    style: {
      fill: ${ui16.fill}
      stroke: ${ui16.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui17: {
    shape: rectangle
    style: {
      fill: ${ui17.fill}
      stroke: ${ui17.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui18: {
    shape: rectangle
    style: {
      fill: ${ui18.fill}
      stroke: ${ui18.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui19: {
    shape: rectangle
    style: {
      fill: ${ui19.fill}
      stroke: ${ui19.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui20: {
    shape: rectangle
    style: {
      fill: ${ui20.fill}
      stroke: ${ui20.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui21: {
    shape: rectangle
    style: {
      fill: ${ui21.fill}
      stroke: ${ui21.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui22: {
    shape: rectangle
    style: {
      fill: ${ui22.fill}
      stroke: ${ui22.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui23: {
    shape: rectangle
    style: {
      fill: ${ui23.fill}
      stroke: ${ui23.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui24: {
    shape: rectangle
    style: {
      fill: ${ui24.fill}
      stroke: ${ui24.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui25: {
    shape: rectangle
    style: {
      fill: ${ui25.fill}
      stroke: ${ui25.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui26: {
    shape: rectangle
    style: {
      fill: ${ui26.fill}
      stroke: ${ui26.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui27: {
    shape: rectangle
    style: {
      fill: ${ui27.fill}
      stroke: ${ui27.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui28: {
    shape: rectangle
    style: {
      fill: ${ui28.fill}
      stroke: ${ui28.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui29: {
    shape: rectangle
    style: {
      fill: ${ui29.fill}
      stroke: ${ui29.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui30: {
    shape: rectangle
    style: {
      fill: ${ui30.fill}
      stroke: ${ui30.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui31: {
    shape: rectangle
    style: {
      fill: ${ui31.fill}
      stroke: ${ui31.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui32: {
    shape: rectangle
    style: {
      fill: ${ui32.fill}
      stroke: ${ui32.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui33: {
    shape: rectangle
    style: {
      fill: ${ui33.fill}
      stroke: ${ui33.stroke}
      stroke-width: 6
      3d: true
    }
  }
  ui34: {
    shape: rectangle
    style: {
      fill: ${ui34.fill}
      stroke: ${ui34.stroke}
      stroke-width: 6
      3d: true
    }
  }
  label_ui0: {
    shape: oval
    style: {
      fill: ${ui0.fill}
      stroke: ${ui0.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui1: {
    shape: oval
    style: {
      fill: ${ui1.fill}
      stroke: ${ui1.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui2: {
    shape: oval
    style: {
      fill: ${ui2.fill}
      stroke: ${ui2.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui3: {
    shape: oval
    style: {
      fill: ${ui3.fill}
      stroke: ${ui3.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui4: {
    shape: oval
    style: {
      fill: ${ui4.fill}
      stroke: ${ui4.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui5: {
    shape: oval
    style: {
      fill: ${ui5.fill}
      stroke: ${ui5.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui6: {
    shape: oval
    style: {
      fill: ${ui6.fill}
      stroke: ${ui6.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui7: {
    shape: oval
    style: {
      fill: ${ui7.fill}
      stroke: ${ui7.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui8: {
    shape: oval
    style: {
      fill: ${ui8.fill}
      stroke: ${ui8.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui9: {
    shape: oval
    style: {
      fill: ${ui9.fill}
      stroke: ${ui9.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui10: {
    shape: oval
    style: {
      fill: ${ui10.fill}
      stroke: ${ui10.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui11: {
    shape: oval
    style: {
      fill: ${ui11.fill}
      stroke: ${ui11.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui12: {
    shape: oval
    style: {
      fill: ${ui12.fill}
      stroke: ${ui12.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui13: {
    shape: oval
    style: {
      fill: ${ui13.fill}
      stroke: ${ui13.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui14: {
    shape: oval
    style: {
      fill: ${ui14.fill}
      stroke: ${ui14.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui15: {
    shape: oval
    style: {
      fill: ${ui15.fill}
      stroke: ${ui15.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui16: {
    shape: oval
    style: {
      fill: ${ui16.fill}
      stroke: ${ui16.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui17: {
    shape: oval
    style: {
      fill: ${ui17.fill}
      stroke: ${ui17.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui18: {
    shape: oval
    style: {
      fill: ${ui18.fill}
      stroke: ${ui18.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui19: {
    shape: oval
    style: {
      fill: ${ui19.fill}
      stroke: ${ui19.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui20: {
    shape: oval
    style: {
      fill: ${ui20.fill}
      stroke: ${ui20.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui21: {
    shape: oval
    style: {
      fill: ${ui21.fill}
      stroke: ${ui21.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui22: {
    shape: oval
    style: {
      fill: ${ui22.fill}
      stroke: ${ui22.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui23: {
    shape: oval
    style: {
      fill: ${ui23.fill}
      stroke: ${ui23.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui24: {
    shape: oval
    style: {
      fill: ${ui24.fill}
      stroke: ${ui24.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui25: {
    shape: oval
    style: {
      fill: ${ui25.fill}
      stroke: ${ui25.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui26: {
    shape: oval
    style: {
      fill: ${ui26.fill}
      stroke: ${ui26.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui27: {
    shape: oval
    style: {
      fill: ${ui27.fill}
      stroke: ${ui27.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui28: {
    shape: oval
    style: {
      fill: ${ui28.fill}
      stroke: ${ui28.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui29: {
    shape: oval
    style: {
      fill: ${ui29.fill}
      stroke: ${ui29.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui30: {
    shape: oval
    style: {
      fill: ${ui30.fill}
      stroke: ${ui30.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui31: {
    shape: oval
    style: {
      fill: ${ui31.fill}
      stroke: ${ui31.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui32: {
    shape: oval
    style: {
      fill: ${ui32.fill}
      stroke: ${ui32.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui33: {
    shape: oval
    style: {
      fill: ${ui33.fill}
      stroke: ${ui33.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
  label_ui34: {
    shape: oval
    style: {
      fill: ${ui34.fill}
      stroke: ${ui34.stroke}
      stroke-width: 6
      font-color: "#003311"
    }
  }
}

# Main container
UITD.style.fill: "#ffffff"
UITD.style.stroke-width: 0
UITD: TOP-Racing {
  A.style.fill: "#eeeeee"
  A.style.stroke-dash: 1
  A: Login {
    0 -> lbl_1_0_3
    lbl_1_0_3 -> 3:{style.stroke-dash:5}
    0 -> lbl_2_0_3
    lbl_2_0_3 -> 3:{style.stroke-dash:5}
    1 -> lbl_3_1_3
    lbl_3_1_3 -> 3:{style.stroke-dash:5}
    0 -> lbl_4_0_1
    lbl_4_0_1 -> 1:{style.stroke-dash:5}
    0 -> lbl_5_0_27
    lbl_5_0_27 -> 27:{style.stroke-dash:5}
    27 -> lbl_6_27_3
    lbl_6_27_3 -> 3:{style.stroke-dash:5}
    1 -> lbl_7_1_27
    lbl_7_1_27 -> 27:{style.stroke-dash:5}
    32 -> lbl_8_32_1
    lbl_8_32_1 -> 1:{style.stroke-dash:5}
    27 -> lbl_9_27_32
    lbl_9_27_32 -> 32:{style.stroke-dash:5}
    1 -> lbl_10_1_31
    lbl_10_1_31 -> 31:{style.stroke-dash:5}
    31 -> lbl_11_31_1
    lbl_11_31_1 -> 1:{style.stroke-dash:5}
    1 -> lbl_12_1_33
    lbl_12_1_33 -> 33:{style.stroke-dash:5}
    33 -> lbl_13_33_1
    lbl_13_33_1 -> 1:{style.stroke-dash:5}
    7 -> lbl_14_7_1
    lbl_14_7_1 -> 1:{style.stroke-dash:5}
    7 -> lbl_15_7_7
    lbl_15_7_7 -> 7:{style.stroke-dash:5}
    7 -> lbl_16_7_7
    lbl_16_7_7 -> 7:{style.stroke-dash:5}
    7 -> lbl_17_7_7
    lbl_17_7_7 -> 7:{style.stroke-dash:5}
    5 -> lbl_18_5_7
    lbl_18_5_7 -> 7:{style.stroke-dash:5}
    5 -> lbl_19_5_7
    lbl_19_5_7 -> 7:{style.stroke-dash:5}
    7 -> lbl_20_7_5
    lbl_20_7_5 -> 5:{style.stroke-dash:5}
    5 -> lbl_21_5_5
    lbl_21_5_5 -> 5:{style.stroke-dash:5}
    5 -> lbl_22_5_5
    lbl_22_5_5 -> 5:{style.stroke-dash:5}
    5 -> lbl_23_5_5
    lbl_23_5_5 -> 5:{style.stroke-dash:5}
    0 -> lbl_24_0_5
    lbl_24_0_5 -> 5:{style.stroke-dash:5}
    0 -> lbl_25_0_2
    lbl_25_0_2 -> 2:{style.stroke-dash:5}
    0 -> lbl_26_0_4
    lbl_26_0_4 -> 4:{style.stroke-dash:5}
    4 -> lbl_27_4_4
    lbl_27_4_4 -> 4:{style.stroke-dash:5}
    4 -> lbl_28_4_4
    lbl_28_4_4 -> 4:{style.stroke-dash:5}
    4 -> lbl_29_4_4
    lbl_29_4_4 -> 4:{style.stroke-dash:5}
    0 -> lbl_30_0_6
    lbl_30_0_6 -> 6:{style.stroke-dash:5}
    6 -> lbl_31_6_6
    lbl_31_6_6 -> 6:{style.stroke-dash:5}
    7 -> lbl_32_7_34
    lbl_32_7_34 -> 34:{style.stroke-dash:5}
    34 -> lbl_33_34_7
    lbl_33_34_7 -> 7:{style.stroke-dash:5}
    7 -> lbl_34_7_8
    lbl_34_7_8 -> 8:{style.stroke-dash:5}
    8 -> lbl_35_8_7
    lbl_35_8_7 -> 7:{style.stroke-dash:5}
    8 -> lbl_36_8_8
    lbl_36_8_8 -> 8:{style.stroke-dash:5}
    8 -> lbl_37_8_8
    lbl_37_8_8 -> 8:{style.stroke-dash:5}
    8 -> lbl_38_8_9
    lbl_38_8_9 -> 9:{style.stroke-dash:5}
    9 -> lbl_39_9_8
    lbl_39_9_8 -> 8:{style.stroke-dash:5}
    9 -> lbl_40_9_9
    lbl_40_9_9 -> 9:{style.stroke-dash:5}
    9 -> lbl_41_9_10
    lbl_41_9_10 -> 10:{style.stroke-dash:5}
    10 -> lbl_42_10_9
    lbl_42_10_9 -> 9:{style.stroke-dash:5}
    10 -> lbl_43_10_9
    lbl_43_10_9 -> 9:{style.stroke-dash:5}
    9 -> lbl_44_9_11
    lbl_44_9_11 -> 11:{style.stroke-dash:5}
    11 -> lbl_45_11_9
    lbl_45_11_9 -> 9:{style.stroke-dash:5}
    11 -> lbl_46_11_12
    lbl_46_11_12 -> 12:{style.stroke-dash:5}
    11 -> lbl_47_11_12
    lbl_47_11_12 -> 12:{style.stroke-dash:5}
    12 -> lbl_48_12_11
    lbl_48_12_11 -> 11:{style.stroke-dash:5}
    12 -> lbl_49_12_12
    lbl_49_12_12 -> 12:{style.stroke-dash:5}
    7 -> lbl_50_7_13
    lbl_50_7_13 -> 13:{style.stroke-dash:5}
    13 -> lbl_51_13_7
    lbl_51_13_7 -> 7:{style.stroke-dash:5}
    13 -> lbl_52_13_7
    lbl_52_13_7 -> 7:{style.stroke-dash:5}
    13 -> lbl_53_13_13
    lbl_53_13_13 -> 13:{style.stroke-dash:5}
    13 -> lbl_54_13_14
    lbl_54_13_14 -> 14:{style.stroke-dash:5}
    13 -> lbl_55_13_14
    lbl_55_13_14 -> 14:{style.stroke-dash:5}
    14 -> lbl_56_14_13
    lbl_56_14_13 -> 13:{style.stroke-dash:5}
    14 -> lbl_57_14_14
    lbl_57_14_14 -> 14:{style.stroke-dash:5}
    14 -> lbl_58_14_15
    lbl_58_14_15 -> 15:{style.stroke-dash:5}
    15 -> lbl_59_15_14
    lbl_59_15_14 -> 14:{style.stroke-dash:5}
    15 -> lbl_60_15_14
    lbl_60_15_14 -> 14:{style.stroke-dash:5}
    15 -> lbl_61_15_15
    lbl_61_15_15 -> 15:{style.stroke-dash:5}
    15 -> lbl_62_15_28
    lbl_62_15_28 -> 28:{style.stroke-dash:5}
    28 -> lbl_63_28_15
    lbl_63_28_15 -> 15:{style.stroke-dash:5}
    28 -> lbl_64_28_28
    lbl_64_28_28 -> 28:{style.stroke-dash:5}
    15 -> lbl_65_15_16
    lbl_65_15_16 -> 16:{style.stroke-dash:5}
    15 -> lbl_66_15_16
    lbl_66_15_16 -> 16:{style.stroke-dash:5}
    16 -> lbl_67_16_15
    lbl_67_16_15 -> 15:{style.stroke-dash:5}
    16 -> lbl_68_16_16
    lbl_68_16_16 -> 16:{style.stroke-dash:5}
    16 -> lbl_69_16_17
    lbl_69_16_17 -> 17:{style.stroke-dash:5}
    17 -> lbl_70_17_16
    lbl_70_17_16 -> 16:{style.stroke-dash:5}
    17 -> lbl_71_17_16
    lbl_71_17_16 -> 16:{style.stroke-dash:5}
    17 -> lbl_72_17_17
    lbl_72_17_17 -> 17:{style.stroke-dash:5}
    17 -> lbl_73_17_18
    lbl_73_17_18 -> 18:{style.stroke-dash:5}
    17 -> lbl_74_17_18
    lbl_74_17_18 -> 18:{style.stroke-dash:5}
    18 -> lbl_75_18_17
    lbl_75_18_17 -> 17:{style.stroke-dash:5}
    18 -> lbl_76_18_18
    lbl_76_18_18 -> 18:{style.stroke-dash:5}
    18 -> lbl_77_18_19
    lbl_77_18_19 -> 19:{style.stroke-dash:5}
    19 -> lbl_78_19_18
    lbl_78_19_18 -> 18:{style.stroke-dash:5}
    19 -> lbl_79_19_18
    lbl_79_19_18 -> 18:{style.stroke-dash:5}
    19 -> lbl_80_19_19
    lbl_80_19_19 -> 19:{style.stroke-dash:5}
    19 -> lbl_81_19_20
    lbl_81_19_20 -> 20:{style.stroke-dash:5}
    19 -> lbl_82_19_20
    lbl_82_19_20 -> 20:{style.stroke-dash:5}
    20 -> lbl_83_20_19
    lbl_83_20_19 -> 19:{style.stroke-dash:5}
    20 -> lbl_84_20_20
    lbl_84_20_20 -> 20:{style.stroke-dash:5}
    20 -> lbl_85_20_21
    lbl_85_20_21 -> 21:{style.stroke-dash:5}
    21 -> lbl_86_21_20
    lbl_86_21_20 -> 20:{style.stroke-dash:5}
    21 -> lbl_87_21_20
    lbl_87_21_20 -> 20:{style.stroke-dash:5}
    21 -> lbl_88_21_21
    lbl_88_21_21 -> 21:{style.stroke-dash:5}
    21 -> lbl_89_21_22
    lbl_89_21_22 -> 22:{style.stroke-dash:5}
    21 -> lbl_90_21_22
    lbl_90_21_22 -> 22:{style.stroke-dash:5}
    22 -> lbl_91_22_21
    lbl_91_22_21 -> 21:{style.stroke-dash:5}
    22 -> lbl_92_22_22
    lbl_92_22_22 -> 22:{style.stroke-dash:5}
    22 -> lbl_93_22_23
    lbl_93_22_23 -> 23:{style.stroke-dash:5}
    23 -> lbl_94_23_22
    lbl_94_23_22 -> 22:{style.stroke-dash:5}
    23 -> lbl_95_23_22
    lbl_95_23_22 -> 22:{style.stroke-dash:5}
    23 -> lbl_96_23_23
    lbl_96_23_23 -> 23:{style.stroke-dash:5}
    23 -> lbl_97_23_24
    lbl_97_23_24 -> 24:{style.stroke-dash:5}
    23 -> lbl_98_23_24
    lbl_98_23_24 -> 24:{style.stroke-dash:5}
    24 -> lbl_99_24_23
    lbl_99_24_23 -> 23:{style.stroke-dash:5}
    24 -> lbl_100_24_24
    lbl_100_24_24 -> 24:{style.stroke-dash:5}
    24 -> lbl_101_24_25
    lbl_101_24_25 -> 25:{style.stroke-dash:5}
    25 -> lbl_102_25_24
    lbl_102_25_24 -> 24:{style.stroke-dash:5}
    25 -> lbl_103_25_24
    lbl_103_25_24 -> 24:{style.stroke-dash:5}
    25 -> lbl_104_25_25
    lbl_104_25_25 -> 25:{style.stroke-dash:5}
    25 -> lbl_105_25_26
    lbl_105_25_26 -> 26:{style.stroke-dash:5}
    25 -> lbl_106_25_26
    lbl_106_25_26 -> 26:{style.stroke-dash:5}
    26 -> lbl_107_26_25
    lbl_107_26_25 -> 25:{style.stroke-dash:5}
    26 -> lbl_108_26_26
    lbl_108_26_26 -> 26:{style.stroke-dash:5}
    lbl_1_0_3.class: label_ui0
    lbl_1_0_3: clicks "Welcome\nPage"
    lbl_2_0_3.class: label_ui0
    lbl_2_0_3: clicks "Logout"\nAND (has an open\nsession)
    lbl_3_1_3.class: label_ui1
    lbl_3_1_3: clicks "Login"\nAND\n(e-mail/password\ncorrect)
    lbl_4_0_1.class: label_ui0
    lbl_4_0_1: clicks "Login"\nAND (has no open\nsession)
    lbl_5_0_27.class: label_ui0
    lbl_5_0_27: clicks "Edit\nProfile" AND\n(has an open\nsession)
    lbl_6_27_3.class: label_ui27
    lbl_6_27_3: clicks "Save\nData" AND (Data\nis saved)
    lbl_7_1_27.class: label_ui1
    lbl_7_1_27: clicks "Create\nAccount"
    lbl_8_32_1.class: label_ui32
    lbl_8_32_1: clicks "OK"
    lbl_9_27_32.class: label_ui27
    lbl_9_27_32: clicks "Save\nData" AND\n(Creation fails)
    lbl_10_1_31.class: label_ui1
    lbl_10_1_31: clicks "Login"\nAND (e-mail or\npassword\nincorrect)
    lbl_11_31_1.class: label_ui31
    lbl_11_31_1: clicks "OK"
    lbl_12_1_33.class: label_ui1
    lbl_12_1_33: clicks "Request\na password\nreset" AND\n(email given)
    lbl_13_33_1.class: label_ui33
    lbl_13_33_1: clicks "OK"
    lbl_14_7_1.class: label_ui7
    lbl_14_7_1: clicks\n"View/Edit Event\nregistrations"\nAND (is not\nlogged in)
    lbl_15_7_7.class: label_ui7
    lbl_15_7_7: clicks\n"Previous"
    lbl_16_7_7.class: label_ui7
    lbl_16_7_7: clicks "Next"
    lbl_17_7_7.class: label_ui7
    lbl_17_7_7: clicks "Save\nData" AND (is\nthe event\ncreator)
    lbl_18_5_7.class: label_ui5
    lbl_18_5_7: clicks "on an\nEvent"
    lbl_19_5_7.class: label_ui5
    lbl_19_5_7: clicks "Create\nEvent"
    lbl_20_7_5.class: label_ui7
    lbl_20_7_5: clicks "Return"
    lbl_21_5_5.class: label_ui5
    lbl_21_5_5: types "in a\nsearch field"
    lbl_22_5_5.class: label_ui5
    lbl_22_5_5: selects\n"territorial\nlevel"
    lbl_23_5_5.class: label_ui5
    lbl_23_5_5: selects\n"temporal level"
    lbl_24_0_5.class: label_ui0
    lbl_24_0_5: clicks "Event\nPriorities"
    lbl_25_0_2.class: label_ui0
    lbl_25_0_2: clicks "Contact"
    lbl_26_0_4.class: label_ui0
    lbl_26_0_4: clicks\n"Standings"
    lbl_27_4_4.class: label_ui4
    lbl_27_4_4: types "in a\nsearch field"
    lbl_28_4_4.class: label_ui4
    lbl_28_4_4: selects\n"territorial\nlevel"
    lbl_29_4_4.class: label_ui4
    lbl_29_4_4: selects\n"temporal level"
    lbl_30_0_6.class: label_ui0
    lbl_30_0_6: clicks "Past\nRegistrations"
    lbl_31_6_6.class: label_ui6
    lbl_31_6_6: types "in a\nsearch field"
    lbl_32_7_34.class: label_ui7
    lbl_32_7_34: clicks "Next\nStatus"
    lbl_33_34_7.class: label_ui34
    lbl_33_34_7: clicks "OK"
    lbl_34_7_8.class: label_ui7
    lbl_34_7_8: clicks\n"View/Edit Event\nregistrations"\nAND (is logged\nin)
    lbl_35_8_7.class: label_ui8
    lbl_35_8_7: clicks "Return"
    lbl_36_8_8.class: label_ui8
    lbl_36_8_8: selects\n"Registration\nstatus" AND (is\nEvent creator)
    lbl_37_8_8.class: label_ui8
    lbl_37_8_8: clicks "Save\nData" AND (is\nEvent creator)
    lbl_38_8_9.class: label_ui8
    lbl_38_8_9: clicks "Create\nRegistration"
    lbl_39_9_8.class: label_ui9
    lbl_39_9_8: clicks "Return"
    lbl_40_9_9.class: label_ui9
    lbl_40_9_9: clicks "Save\nData" AND (is\nRegistration\ncreator)
    lbl_41_9_10.class: label_ui9
    lbl_41_9_10: clicks "View\nDrivers" AND (is\nRegistration\ncreator)
    lbl_42_10_9.class: label_ui10
    lbl_42_10_9: selects "Driver"
    lbl_43_10_9.class: label_ui10
    lbl_43_10_9: clicks "Return"
    lbl_44_9_11.class: label_ui9
    lbl_44_9_11: clicks "View\nVehicles" AND\n(is Registration\ncreator)
    lbl_45_11_9.class: label_ui11
    lbl_45_11_9: selects\n"Vehicle"
    lbl_46_11_12.class: label_ui11
    lbl_46_11_12: clicks "Create\nVehicle"
    lbl_47_11_12.class: label_ui11
    lbl_47_11_12: clicks "on a\nVehicle"
    lbl_48_12_11.class: label_ui12
    lbl_48_12_11: clicks "Return"
    lbl_49_12_12.class: label_ui12
    lbl_49_12_12: clicks "Save\nData"
    lbl_50_7_13.class: label_ui7
    lbl_50_7_13: clicks "View\nVariants"
    lbl_51_13_7.class: label_ui13
    lbl_51_13_7: clicks "Select"\nAND (is Event\ncreator)
    lbl_52_13_7.class: label_ui13
    lbl_52_13_7: clicks "Return"
    lbl_53_13_13.class: label_ui13
    lbl_53_13_13: types "in a\nsearch field"
    lbl_54_13_14.class: label_ui13
    lbl_54_13_14: clicks "Create\nVariant"
    lbl_55_13_14.class: label_ui13
    lbl_55_13_14: clicks "on a\nVariant"
    lbl_56_14_13.class: label_ui14
    lbl_56_14_13: clicks "Return"
    lbl_57_14_14.class: label_ui14
    lbl_57_14_14: clicks "Save\nData" AND (is\nthe variant\ncreator)
    lbl_58_14_15.class: label_ui14
    lbl_58_14_15: clicks "View\nVenues"
    lbl_59_15_14.class: label_ui15
    lbl_59_15_14: clicks "Select"\nAND (is Variant\ncreator)
    lbl_60_15_14.class: label_ui15
    lbl_60_15_14: clicks "Return"
    lbl_61_15_15.class: label_ui15
    lbl_61_15_15: types "in a\nsearch field"
    lbl_62_15_28.class: label_ui15
    lbl_62_15_28: clicks "View in\nMap"
    lbl_63_28_15.class: label_ui28
    lbl_63_28_15: clicks "Return"
    lbl_64_28_28.class: label_ui28
    lbl_64_28_28: clicks "on Map"\nAND (is the\nvenue creator)
    lbl_65_15_16.class: label_ui15
    lbl_65_15_16: clicks "Create\nVenue"
    lbl_66_15_16.class: label_ui15
    lbl_66_15_16: clicks "on a\nVenue"
    lbl_67_16_15.class: label_ui16
    lbl_67_16_15: clicks "Return"
    lbl_68_16_16.class: label_ui16
    lbl_68_16_16: clicks "Save\nData" AND (is\nthe venue\ncreator)
    lbl_69_16_17.class: label_ui16
    lbl_69_16_17: clicks "View\nProvince\nRegions"
    lbl_70_17_16.class: label_ui17
    lbl_70_17_16: clicks "Select"\nAND (is Venue\ncreator)
    lbl_71_17_16.class: label_ui17
    lbl_71_17_16: clicks "Return"
    lbl_72_17_17.class: label_ui17
    lbl_72_17_17: types "in a\nsearch field"
    lbl_73_17_18.class: label_ui17
    lbl_73_17_18: clicks "Create\nProvince Region"
    lbl_74_17_18.class: label_ui17
    lbl_74_17_18: clicks "on a\nProvince Region"
    lbl_75_18_17.class: label_ui18
    lbl_75_18_17: clicks "Return"
    lbl_76_18_18.class: label_ui18
    lbl_76_18_18: clicks "Save\nData" AND (is\nthe Province\nRegion creator)
    lbl_77_18_19.class: label_ui18
    lbl_77_18_19: clicks "View\nProvinces"
    lbl_78_19_18.class: label_ui19
    lbl_78_19_18: clicks "Select"\nAND (is Province\nRegion creator)
    lbl_79_19_18.class: label_ui19
    lbl_79_19_18: clicks "Return"
    lbl_80_19_19.class: label_ui19
    lbl_80_19_19: types "in a\nsearch field"
    lbl_81_19_20.class: label_ui19
    lbl_81_19_20: clicks "Create\nProvince"
    lbl_82_19_20.class: label_ui19
    lbl_82_19_20: clicks "on a\nProvince"
    lbl_83_20_19.class: label_ui20
    lbl_83_20_19: clicks "Return"
    lbl_84_20_20.class: label_ui20
    lbl_84_20_20: clicks "Save\nData" AND (is\nthe Province\ncreator)
    lbl_85_20_21.class: label_ui20
    lbl_85_20_21: clicks "View\nCountry Regions"
    lbl_86_21_20.class: label_ui21
    lbl_86_21_20: clicks "Select"\nAND (is Province\ncreator)
    lbl_87_21_20.class: label_ui21
    lbl_87_21_20: clicks "Return"
    lbl_88_21_21.class: label_ui21
    lbl_88_21_21: types "in a\nsearch field"
    lbl_89_21_22.class: label_ui21
    lbl_89_21_22: clicks "Create\nCountry Region"
    lbl_90_21_22.class: label_ui21
    lbl_90_21_22: clicks "on a\nCountry Region"
    lbl_91_22_21.class: label_ui22
    lbl_91_22_21: clicks "Return"
    lbl_92_22_22.class: label_ui22
    lbl_92_22_22: clicks "Save\nData" AND (is\nthe Country\nRegion creator)
    lbl_93_22_23.class: label_ui22
    lbl_93_22_23: clicks "View\nCountries"
    lbl_94_23_22.class: label_ui23
    lbl_94_23_22: clicks "Select"\nAND (is Country\nRegion creator)
    lbl_95_23_22.class: label_ui23
    lbl_95_23_22: clicks "Return"
    lbl_96_23_23.class: label_ui23
    lbl_96_23_23: types "in a\nsearch field"
    lbl_97_23_24.class: label_ui23
    lbl_97_23_24: clicks "Create\nCountry"
    lbl_98_23_24.class: label_ui23
    lbl_98_23_24: clicks "on a\nCountry"
    lbl_99_24_23.class: label_ui24
    lbl_99_24_23: clicks "Return"
    lbl_100_24_24.class: label_ui24
    lbl_100_24_24: clicks "Save\nData" AND (is\nCountry creator)
    lbl_101_24_25.class: label_ui24
    lbl_101_24_25: clicks "View\nPlanet Regions"
    lbl_102_25_24.class: label_ui25
    lbl_102_25_24: clicks "Select"\nAND (is Country\ncreator)
    lbl_103_25_24.class: label_ui25
    lbl_103_25_24: clicks "Return"
    lbl_104_25_25.class: label_ui25
    lbl_104_25_25: types "in a\nsearch field"
    lbl_105_25_26.class: label_ui25
    lbl_105_25_26: clicks "Create\nPlanet Region"
    lbl_106_25_26.class: label_ui25
    lbl_106_25_26: clicks "on a\nPlanet Region"
    lbl_107_26_25.class: label_ui26
    lbl_107_26_25: clicks "Return"
    lbl_108_26_26.class: label_ui26
    lbl_108_26_26: clicks "Save\nData" AND (is\nPlanet Region\ncreator)
    0.class: ui0
    0: 0 Navigation
    3.class: ui3
    3: 3 Welcome {
      0.class: ui0
      0.style.stroke-dash: 5
      0: 0 Navigation
    }
    1.class: ui1
    1: 1 Login {
      0.class: ui0
      0.style.stroke-dash: 5
      0: 0 Navigation
    }
    27.class: ui27
    27: 27 Edit Profile {
      0.class: ui0
      0.style.stroke-dash: 5
      0: 0 Navigation
    }
    32.class: ui32
    32: 32 Account Creation\nFailed Alert
    31.class: ui31
    31: 31 Login Failed Alert
    33.class: ui33
    33: 33 Password Reset\nSuccess Alert
    5.class: ui5
    5: 5 Priorities {
      0.class: ui0
      0.style.stroke-dash: 5
      0: 0 Navigation
    }
    7.class: ui7
    7: 7 View/Edit Event
    2.class: ui2
    2: 2 Contact {
      0.class: ui0
      0.style.stroke-dash: 5
      0: 0 Navigation
    }
    4.class: ui4
    4: 4 Standings {
      0.class: ui0
      0.style.stroke-dash: 5
      0: 0 Navigation
    }
    6.class: ui6
    6: 6 Past Registrations {
      0.class: ui0
      0.style.stroke-dash: 5
      0: 0 Navigation
    }
    29.class: ui29
    29.style.stroke-dash: 5
    29: 29 Forum
    30.class: ui30
    30.style.stroke-dash: 5
    30: 30 News
    34.class: ui34
    34: 34 Next Status Alert
    8.class: ui8
    8: 8 View/Edit Event\nRegistrations
    9.class: ui9
    9: 9 View/Edit\nRegistration
    10.class: ui10
    10: 10 View Drivers
    11.class: ui11
    11: 11 View Vehicles
    12.class: ui12
    12: 12 Edit Vehicle
    13.class: ui13
    13: 13 Variants
    14.class: ui14
    14: 14 View/Edit Variant
    15.class: ui15
    15: 15 Venues
    28.class: ui28
    28: 28 Map
    16.class: ui16
    16: 16 View/Edit Venue
    17.class: ui17
    17: 17 Province Regions
    18.class: ui18
    18: 18 View/Edit Province\nRegion
    19.class: ui19
    19: 19 Provinces
    20.class: ui20
    20: 20 View/Edit Province
    21.class: ui21
    21: 21 Country Regions
    22.class: ui22
    22: 22 View/Edit Country\nRegion
    23.class: ui23
    23: 23 Countries
    24.class: ui24
    24: 24 View/Edit Country
    25.class: ui25
    25: 25 Planet Regions
    26.class: ui26
    26: 26 View/Edit Planet\nRegion
  }
}
